# Generated by Django 4.1.3 on 2022-11-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='value',
            field=models.IntegerField(),
        ),
    ]
