# Generated by Django 4.1.3 on 2022-11-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogAPI', '0002_alter_key_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='assets/')),
            ],
        ),
        migrations.AlterField(
            model_name='key',
            name='key',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
