# Generated by Django 4.1.3 on 2022-11-20 14:31

from django.db import migrations
import exiffield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dogAPI', '0003_cachedimage_alter_key_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedimage',
            name='exif',
            field=exiffield.fields.ExifField(default={}, editable=False),
        ),
    ]
