# Generated by Django 4.1.3 on 2022-11-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogAPI', '0004_cachedimage_exif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedimage',
            name='photo',
            field=models.ImageField(blank=True, upload_to='dogapi/assets/'),
        ),
    ]
